use super::AOC_URL;
use crate::domain::{
    ports::{errors::AocClientError, get_stars::GetStars},
    solved_parts::SolvedParts,
    stars::Stars,
};

use super::AocApi;

impl GetStars for AocApi {
    fn get_stars(&self, year: i32) -> Result<Stars, AocClientError> {
        let url = reqwest::Url::parse(&format!("{}/{}", AOC_URL, year))?;
        Stars::from_readable(self.http_client.get(url).send()?.error_for_status()?)
    }
}

// It's impossible to implement the trait
// impl<T: std::io::Read> TryFrom<T> for Stars
// because there is already a blanket implementation
// of this trait in the standard library which conflicts
// with the one above. So this is one workaround...
impl Stars {
    pub fn from_readable<T: std::io::Read>(mut readable: T) -> Result<Stars, AocClientError> {
        let mut body = String::new();
        readable
            .read_to_string(&mut body)
            .map_err(|_| AocClientError::GetStarsError)?;

        parse_http_response(body)
    }
}

fn parse_http_response(calendar_http_body: String) -> Result<Stars, AocClientError> {
    let document = scraper::Html::parse_document(&calendar_http_body);
    let calendar_entries_selector =
        scraper::Selector::parse("[class^='calendar-day']:not(.calendar-day)").unwrap();
    let solved_parts = document
        .select(&calendar_entries_selector)
        .map(|day| {
            match (
                day.value()
                    .classes()
                    .any(|class| class == "calendar-complete"),
                day.value()
                    .classes()
                    .any(|class| class == "calendar-verycomplete"),
            ) {
                (false, false) => SolvedParts::None,
                (true, false) => SolvedParts::One,
                (_, _) => SolvedParts::Both,
            }
        })
        .collect::<Vec<_>>();
    let calendar_entries = document
        .select(&calendar_entries_selector)
        .collect::<Vec<_>>();

    let entries_without_stars = std::iter::zip(solved_parts.clone(), calendar_entries)
        .map(|(solved_part, entry)| {
            let text = entry.text().collect::<Vec<_>>();
            Ok(match solved_part {
                SolvedParts::Both => text.join(""),
                SolvedParts::One => text
                    .join("")
                    .strip_suffix("*")
                    .ok_or_else(|| AocClientError::GetStarsError)?
                    .to_owned(),
                SolvedParts::None => text
                    .join("")
                    .strip_suffix("**")
                    .ok_or_else(|| AocClientError::GetStarsError)?
                    .to_owned(),
            })
        })
        .collect::<Result<Vec<String>, AocClientError>>()?;
    Ok(Stars::new(solved_parts, entries_without_stars))
}

#[cfg(test)]
mod tests {
    use std::{fs::File, io::BufReader, path::PathBuf};

    use super::*;

    #[test]
    fn parsing_no_stars_page() {
        let calendar = r#"
<pre class="calendar"><a aria-label="Day 25" href="/2019/day/25" class="calendar-day25">     <span class="calendar-s">.</span>             ''..     ':.              '.    <span class="calendar-day">25</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 24" href="/2019/day/24" class="calendar-day24">.......              <span class="calendar-s">.</span> ''.  <span class="calendar-s">.</span>  '.              :   <span class="calendar-day">24</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 23" href="/2019/day/23" class="calendar-day23">       '''''... <span class="calendar-s">.</span>         ''.    '.            <span class="calendar-s">.</span>'  <span class="calendar-day">23</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 22" href="/2019/day/22" class="calendar-day22">               ''..          '.  <span class="calendar-s">.</span> '.              <span class="calendar-day">22</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 21" href="/2019/day/21" class="calendar-day21">......   <span class="calendar-s">.</span><span class="calendar-s">.</span>        ''.         '.    '.            <span class="calendar-day">21</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 20" href="/2019/day/20" class="calendar-day20">      ''''...        <span class="calendar-s">.</span>'. <span class="calendar-s">.</span>       '.    :           <span class="calendar-day">20</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 19" href="/2019/day/19" class="calendar-day19">             ''..       '.         '.   '.  <span class="calendar-s">.</span><span class="calendar-s">.</span>     <span class="calendar-day">19</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 18" href="/2019/day/18" class="calendar-day18">.....       <span class="calendar-s">.</span>    ''.      '.<span class="calendar-s">.</span>       '.   '.        <span class="calendar-day">18</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 17" href="/2019/day/17" class="calendar-day17">  <span class="calendar-s">.</span>  ''''...  <span class="calendar-s">.</span>     '.      '.  <span class="calendar-s">.</span>    ': <span class="calendar-s">.</span> '.       <span class="calendar-day">17</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 16" href="/2019/day/16" class="calendar-day16">            '..  <span class="calendar-s">.</span>    '.      '.       :    :      <span class="calendar-day">16</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 15" href="/2019/day/15" class="calendar-day15">          <span class="calendar-s">.</span>    '.       '.     '.       :    :     <span class="calendar-day">15</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 14" href="/2019/day/14" class="calendar-day14">'''''...         '. <span class="calendar-s">.</span> <span class="calendar-s">.</span>  '.     '.       :   '.    <span class="calendar-day">14</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 13" href="/2019/day/13" class="calendar-day13">      <span class="calendar-s">.</span> ''..       '.     '.     '.      '.  <span class="calendar-s">.</span>:    <span class="calendar-day">13</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 12" href="/2019/day/12" class="calendar-day12">''''...  <span class="calendar-s">.</span><span class="calendar-s">.</span> '.      '.     '. <span class="calendar-s">.</span>   '.      :    :<span class="calendar-s">.</span>  <span class="calendar-day">12</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 11" href="/2019/day/11" class="calendar-day11">       ''.    '.   <span class="calendar-s">.</span>  :     '. <span class="calendar-s">.</span>   :      '. <span class="calendar-s">.</span> :   <span class="calendar-day">11</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 10" href="/2019/day/10" class="calendar-day10">'''''..   '.   '.      :     :  <span class="calendar-s">.</span>  '.      :   '.  <span class="calendar-day">10</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 9" href="/2019/day/9" class="calendar-day9">       '.  '.   '.     '.     :     :      :    :  <span class="calendar-day"> 9</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 8" href="/2019/day/8" class="calendar-day8">         :  '. <span class="calendar-s">.</span> :      :     :     :     <span class="calendar-s">.</span> :   :  <span class="calendar-day"> 8</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 7" href="/2019/day/7" class="calendar-day7">'''.      : <span class="calendar-s">.</span>:   :      :     :     :   <span class="calendar-s">.</span>   :   :  <span class="calendar-day"> 7</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 6" href="/2019/day/6" class="calendar-day6">   :   <span class="calendar-s">.</span>  :  :   :     <span class="calendar-s">.</span>:     : <span class="calendar-s">.</span>   :       :   :  <span class="calendar-day"> 6</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 5" href="/2019/day/5" class="calendar-day5">...'      :  :   :      :     :     :       :   :  <span class="calendar-day"> 5</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 4" href="/2019/day/4" class="calendar-day4">         :  .'   :      :     :<span class="calendar-s">.</span>    :  <span class="calendar-s">.</span>    :   :  <span class="calendar-day"> 4</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 3" href="/2019/day/3" class="calendar-day3">     <span class="calendar-s">.</span> .'  .'   .'     .'<span class="calendar-s">.</span>    :   <span class="calendar-s">.</span> :      :    :  <span class="calendar-day"> 3</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 2" href="/2019/day/2" class="calendar-day2">.....''   .'   .'      :     :     .'<span class="calendar-s">.</span>    <span class="calendar-s">.</span>:<span class="calendar-s">.</span>  .'  <span class="calendar-day"> 2</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 1" href="/2019/day/1" class="calendar-day1">       ..'    .'  <span class="calendar-s">.</span>   :<span class="calendar-s">.</span>    .'     :     <span class="calendar-s">.</span>.'   :   <span class="calendar-day"> 1</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
        </pre>"#.to_owned();

        let stars = parse_http_response(calendar).unwrap();
        assert!(stars.pattern.len() == 25);
        assert!(stars.stars.len() == 25);
        assert!(stars.stars.last().unwrap() == &SolvedParts::None);
    }

    #[test]
    fn parsing_partial_completion_one_star() {
        let calendar = r#"
<pre class="calendar"><a aria-label="Day 25" href="/2018/day/25" class="calendar-day25">                                                   <span class="calendar-day">25</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 24" href="/2018/day/24" class="calendar-day24">                                                   <span class="calendar-day">24</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 23" href="/2018/day/23" class="calendar-day23">                                                   <span class="calendar-day">23</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 22" href="/2018/day/22" class="calendar-day22">                                                   <span class="calendar-day">22</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 21" href="/2018/day/21" class="calendar-day21">                                                   <span class="calendar-day">21</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 20" href="/2018/day/20" class="calendar-day20">                                                   <span class="calendar-day">20</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 19" href="/2018/day/19" class="calendar-day19">                                                   <span class="calendar-day">19</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 18" href="/2018/day/18" class="calendar-day18">                                                   <span class="calendar-day">18</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 17" href="/2018/day/17" class="calendar-day17">                                                   <span class="calendar-day">17</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 16" href="/2018/day/16" class="calendar-day16">                                                   <span class="calendar-day">16</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 15" href="/2018/day/15" class="calendar-day15">                                                   <span class="calendar-day">15</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 14" href="/2018/day/14" class="calendar-day14">                                                   <span class="calendar-day">14</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 13" href="/2018/day/13" class="calendar-day13">                                                   <span class="calendar-day">13</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 12" href="/2018/day/12" class="calendar-day12">                                                   <span class="calendar-day">12</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 11" href="/2018/day/11" class="calendar-day11">                                                   <span class="calendar-day">11</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 10" href="/2018/day/10" class="calendar-day10">                                                   <span class="calendar-day">10</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 9" href="/2018/day/9" class="calendar-day9">                                                   <span class="calendar-day"> 9</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 8" href="/2018/day/8" class="calendar-day8">                                                   <span class="calendar-day"> 8</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 7" href="/2018/day/7" class="calendar-day7">                                                   <span class="calendar-day"> 7</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 6" href="/2018/day/6" class="calendar-day6">                                                   <span class="calendar-day"> 6</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 5" href="/2018/day/5" class="calendar-day5">                                                   <span class="calendar-day"> 5</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 4" href="/2018/day/4" class="calendar-day4">                                                   <span class="calendar-day"> 4</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 3" href="/2018/day/3" class="calendar-day3">                                                   <span class="calendar-day"> 3</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 2" href="/2018/day/2" class="calendar-day2">                                                   <span class="calendar-day"> 2</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 1, one star" href="/2018/day/1" class="calendar-day1 calendar-complete">                  _  _ __ ___ __ _  _              <span class="calendar-day"> 1</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
</pre>"#.to_owned();
        let stars = parse_http_response(calendar).unwrap();
        assert!(stars.pattern.len() == 25);
        assert!(stars.stars.len() == 25);
        assert!(stars.stars.last().unwrap() == &SolvedParts::One);
    }

    #[test]
    fn parsing_full_completion() {
        let calendar = r#"
<pre class="calendar calendar-perfect"><a aria-label="Day 25, two stars" href="/2022/day/25" class="calendar-day25 calendar-verycomplete"><span class="calendar-color-p">  - </span><span class="calendar-color-w">/\</span><span class="calendar-color-p"> -  -        -       -     -      -    -   </span>
<span class="calendar-color-o"> - </span><span class="calendar-color-a">/</span> <span class="balloon-wind" style="color:hsl(335deg, 100%, 50%); animation-delay:0s;"><span class="balloon" style="animation-delay:0s;"></span></span><span class="balloon-wind" style="color:hsl(359deg, 100%, 50%); animation-delay:4s;"><span class="balloon" style="animation-delay:4s;"></span></span><span class="balloon-wind" style="color:hsl(23deg, 100%, 50%); animation-delay:8s;"><span class="balloon" style="animation-delay:8s;"></span></span><span class="balloon-wind" style="color:hsl(47deg, 100%, 50%); animation-delay:12s;"><span class="balloon" style="animation-delay:12s;"></span></span><span class="balloon-wind" style="color:hsl(71deg, 100%, 50%); animation-delay:16s;"><span class="balloon" style="animation-delay:16s;"></span></span><span class="balloon-wind" style="color:hsl(95deg, 100%, 50%); animation-delay:20s;"><span class="balloon" style="animation-delay:20s;"></span></span><span class="balloon-wind" style="color:hsl(119deg, 100%, 50%); animation-delay:24s;"><span class="balloon" style="animation-delay:24s;"></span></span><span class="balloon-wind" style="color:hsl(143deg, 100%, 50%); animation-delay:28s;"><span class="balloon" style="animation-delay:28s;"></span></span><span class="balloon-wind" style="color:hsl(167deg, 100%, 50%); animation-delay:32s;"><span class="balloon" style="animation-delay:32s;"></span></span><span class="balloon-wind" style="color:hsl(191deg, 100%, 50%); animation-delay:36s;"><span class="balloon" style="animation-delay:36s;"></span></span><span class="balloon-wind" style="color:hsl(215deg, 100%, 50%); animation-delay:40s;"><span class="balloon" style="animation-delay:40s;"></span></span><span class="balloon-wind" style="color:hsl(239deg, 100%, 50%); animation-delay:44s;"><span class="balloon" style="animation-delay:44s;"></span></span><span class="balloon-wind" style="color:hsl(263deg, 100%, 50%); animation-delay:48s;"><span class="balloon" style="animation-delay:48s;"></span></span><span class="balloon-wind" style="color:hsl(287deg, 100%, 50%); animation-delay:52s;"><span class="balloon" style="animation-delay:52s;"></span></span><span class="balloon-wind" style="color:hsl(311deg, 100%, 50%); animation-delay:56s;"><span class="balloon" style="animation-delay:56s;"></span></span> <span class="calendar-color-a">\/\</span><span class="calendar-color-o">  -    -     -  -    -   - </span> <span class="calendar-color-a">/\</span> <span class="calendar-color-o">  -     -</span>
<span class="calendar-color-y"> </span><span class="calendar-color-a">/\</span>    <span class="calendar-color-a">\</span> <span class="calendar-color-a">\</span><span class="calendar-color-y">-  - -   -   -    - -  -</span><span class="calendar-color-a">/\/  \</span><span class="calendar-color-y">-   -  - </span>  <span class="calendar-day">25</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 24, two stars" href="/2022/day/24" class="calendar-day24 calendar-verycomplete"><span class="calendar-color-a">/</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-a">\</span>   <span class="calendar-color-a">/\</span><span class="calendar-color-g4">@</span><span class="calendar-color-a">\</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span>  <span class="calendar-day">24</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 23, two stars" href="/2022/day/23" class="calendar-day23 calendar-verycomplete"><span class="calendar-color-g0">@#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">.'</span><span class="calendar-color-g1"> </span><span class="calendar-color-g3">'</span><span class="calendar-color-g1">.</span><span class="calendar-color-g4">#@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g0">##@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">##</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g2">@@@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span>  <span class="calendar-day">23</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 22, two stars" href="/2022/day/22" class="calendar-day22 calendar-verycomplete"><span class="calendar-color-g0">@#@</span><span class="calendar-color-g1">'</span><span class="calendar-color-g2">. </span><span class="calendar-color-g3">.'@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">##</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">##</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">#@@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-w">()))</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">#</span>  <span class="calendar-day">22</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 21, two stars" href="/2022/day/21" class="calendar-day21 calendar-verycomplete"><span class="calendar-color-g3">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g0">##</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@#</span><span class="calendar-color-g1">@##</span><span class="calendar-color-s">.</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@@@</span><span class="calendar-color-g3">#@</span>  <span class="calendar-day">21</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 20, two stars" href="/2022/day/20" class="calendar-day20 calendar-verycomplete"><span class="calendar-color-g0">#@</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g3">@#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g1">@</span><span class="calendar-color-u">~~</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">#@@@@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">#</span>  <span class="calendar-day">20</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 19, two stars" href="/2022/day/19" class="calendar-day19 calendar-verycomplete"><span class="calendar-color-g0">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g1">#@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-u">.</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">@@@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">#@#</span><span class="calendar-color-g3">@@</span><span class="calendar-color-u">~~~~</span> <span class="calendar-color-a">.~'</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">@##</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g4">@#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span>  <span class="calendar-day">19</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 18, two stars" href="/2022/day/18" class="calendar-day18 calendar-verycomplete"><span class="calendar-color-g0">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g2">#@</span><span class="calendar-color-g3">@</span><span class="calendar-color-u">.</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-u">~~</span> <span class="calendar-color-a">/</span><span class="calendar-color-l">~</span><span class="calendar-color-a">\</span> <span class="calendar-color-g2">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g4">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">#@</span><span class="calendar-color-d">|</span>  <span class="calendar-day">18</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 17, two stars" href="/2022/day/17" class="calendar-day17 calendar-verycomplete"><span class="calendar-color-g0">##</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@#</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-u">..</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g3">@@@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">@</span> <span class="calendar-color-a">/</span> <span class="calendar-color-l">/</span> <span class="calendar-color-a">\</span> <span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span>  <span class="calendar-day">17</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 16, two stars" href="/2022/day/16" class="calendar-day16 calendar-verycomplete"><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g2">@#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-u">..</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#@</span><span class="calendar-color-a">/</span> <span class="calendar-color-l">/</span> <span class="calendar-color-l">\</span> <span class="calendar-color-a">\</span><span class="calendar-color-g2">@@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@@@@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g4">#</span>  <span class="calendar-day">16</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 15, two stars" href="/2022/day/15" class="calendar-day15 calendar-verycomplete"><span class="calendar-color-g3">@#@</span><span class="calendar-color-g4">@#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">_</span><span class="calendar-color-u">.~.</span><span class="calendar-color-g1">_</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-a">.'</span><span class="calendar-color-l">/\</span><span class="calendar-color-a">.'</span><span class="calendar-color-l">~</span><span class="calendar-color-a">.</span> <span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span>  <span class="calendar-day">15</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 14, two stars" href="/2022/day/14" class="calendar-day14 calendar-verycomplete"><span class="calendar-color-g3">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-s">.</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span> <span class="calendar-color-w">|||</span> <span class="calendar-color-g1">@#@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#@</span><span class="calendar-color-g1">@</span><span class="calendar-color-a">'.</span><span class="calendar-color-l">~</span><span class="calendar-color-a">.'</span><span class="calendar-color-l">~</span><span class="calendar-color-a">. </span><span class="calendar-color-l">\</span><span class="calendar-color-a">'.</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g2">@</span>  <span class="calendar-day">14</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 13, two stars" href="/2022/day/13" class="calendar-day13 calendar-verycomplete"><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">@@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g3">@@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-w">~~~</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">#@@</span><span class="calendar-color-a">' ..'.'.</span><span class="calendar-color-l">\</span><span class="calendar-color-a">. . </span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">##</span><span class="calendar-color-g0">@@</span>  <span class="calendar-day">13</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 12, two stars" href="/2022/day/12" class="calendar-day12 calendar-verycomplete"><span class="calendar-color-g2">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">#@</span><span class="calendar-color-g0">#@@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-a"> .'.</span><span class="calendar-color-l">~~~</span><span class="calendar-color-a">' </span><span class="calendar-color-g0">@</span><span class="calendar-color-a">'</span><span class="calendar-color-g1">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span>  <span class="calendar-day">12</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 11, two stars" href="/2022/day/11" class="calendar-day11 calendar-verycomplete"><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@#</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g1">##</span><span class="calendar-color-g4">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#@</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">#@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-a">  </span><span class="calendar-color-l">~~~~~</span><span class="calendar-color-a">..</span><span class="calendar-color-g3">#@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">#</span>  <span class="calendar-day">11</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 10, two stars" href="/2022/day/10" class="calendar-day10 calendar-verycomplete"><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@#</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g2">#@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">@@</span><span class="calendar-color-g3">#@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@@@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@#</span><span class="calendar-color-g0">@</span><span class="calendar-color-a">.'</span><span class="calendar-color-l">/</span><span class="calendar-color-a"> </span><span class="calendar-color-l">~~~</span><span class="calendar-color-a"> </span><span class="calendar-color-l">\</span><span class="calendar-color-a">' </span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">#</span>  <span class="calendar-day">10</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 9, two stars" href="/2022/day/9" class="calendar-day9 calendar-verycomplete"><span class="calendar-color-g1">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-s">.</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span> <span class="calendar-color-a">_</span><span class="calendar-color-s">|%%%=%%|</span><span class="calendar-color-a">_</span> <span class="calendar-color-g4">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@#@@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@@</span><span class="calendar-color-a">. </span><span class="calendar-color-l">~</span><span class="calendar-color-a"> </span><span class="calendar-color-l">/</span><span class="calendar-color-a">' .'</span><span class="calendar-color-l">/\</span><span class="calendar-color-a">.</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span>  <span class="calendar-day"> 9</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 8, two stars" href="/2022/day/8" class="calendar-day8 calendar-verycomplete"><span class="calendar-color-g4">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-s">..</span><span class="calendar-color-a">/  \</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-a">/  \</span><span class="calendar-color-s">.....</span><span class="calendar-color-g4">@@</span><span class="calendar-color-g3">#@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">#</span><span class="calendar-color-g1">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-a">' </span><span class="calendar-color-l">/\</span><span class="calendar-color-a">.''</span><span class="calendar-color-l">/</span><span class="calendar-color-a">' </span><span class="calendar-color-l">\</span><span class="calendar-color-a">' </span><span class="calendar-color-g3">@#</span><span class="calendar-color-g0">@</span>  <span class="calendar-day"> 8</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 7, two stars" href="/2022/day/7" class="calendar-day7 calendar-verycomplete"><span class="calendar-color-g4">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-s">.</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g2">##</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g0">@</span><span class="calendar-color-a">'.</span><span class="calendar-color-l">/</span><span class="calendar-color-a">.</span><span class="calendar-color-l">/\</span><span class="calendar-color-a"> .</span><span class="calendar-color-l">\</span><span class="calendar-color-a">'.</span><span class="calendar-color-l">/\</span><span class="calendar-color-a"> '. </span>  <span class="calendar-day"> 7</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 6, two stars" href="/2022/day/6" class="calendar-day6 calendar-verycomplete"><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">@#</span><span class="calendar-color-g2">#@#@</span><span class="calendar-color-g0">@</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g4">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-s">..</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-a">' </span><span class="calendar-color-l">~</span><span class="calendar-color-a">. </span><span class="calendar-color-l">\</span><span class="calendar-color-a">.</span><span class="calendar-color-l">\</span><span class="calendar-color-a">  </span><span class="calendar-color-l">\</span><span class="calendar-color-a"> </span><span class="calendar-color-l">\</span><span class="calendar-color-a">.</span><span class="calendar-color-l">~~~</span><span class="calendar-color-a">.</span>  <span class="calendar-day"> 6</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 5, two stars" href="/2022/day/5" class="calendar-day5 calendar-verycomplete"><span class="calendar-color-g2">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g1">@@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">##</span><span class="calendar-color-g3">#</span><span class="calendar-color-u">.~~.</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">#</span><span class="calendar-color-s">.</span><span class="calendar-color-c">/\</span><span class="calendar-color-s">.'</span><span class="calendar-color-g1">@</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-a">'.' .'</span><span class="calendar-color-l">/</span><span class="calendar-color-a">.</span><span class="calendar-color-g1">@</span><span class="calendar-color-a">. </span><span class="calendar-color-l">/</span><span class="calendar-color-a">'.</span><span class="calendar-color-l">~~~</span>  <span class="calendar-day"> 5</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 4, two stars" href="/2022/day/4" class="calendar-day4 calendar-verycomplete"><span class="calendar-color-g0">@@@</span><span class="calendar-color-g4">#</span><span class="calendar-color-g2">#</span><span class="calendar-color-g0">@@</span><span class="calendar-color-g3">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g0">#</span><span class="calendar-color-s">.'</span><span class="calendar-color-u"> ~  </span><span class="calendar-color-s">'.</span><span class="calendar-color-c">/\</span><span class="calendar-color-s">'.</span><span class="calendar-color-c">/\</span><span class="calendar-color-s">' .</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g2">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g4">@</span><span class="calendar-color-a">' </span><span class="calendar-color-l">/\</span><span class="calendar-color-a"> . </span><span class="calendar-color-l">/</span><span class="calendar-color-a">'. ..'</span>  <span class="calendar-day"> 4</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 3, two stars" href="/2022/day/3" class="calendar-day3 calendar-verycomplete"><span class="calendar-color-g3">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-g3">@</span><span class="calendar-color-g4">@</span><span class="calendar-color-g1">#</span><span class="calendar-color-g2">@</span><span class="calendar-color-g3">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">#</span><span class="calendar-color-s">_/</span><span class="calendar-color-u"> ~   ~  </span><span class="calendar-color-s">\ ' '. '.'.</span><span class="calendar-color-g3">@</span><span class="calendar-color-g1">@@@</span><span class="calendar-color-a">  </span><span class="calendar-color-l">/</span><span class="calendar-color-a">  </span><span class="calendar-color-l">\</span><span class="calendar-color-a">  </span><span class="calendar-color-l">\</span><span class="calendar-color-a">  </span><span class="calendar-color-g2">#</span><span class="calendar-color-g1">@</span><span class="calendar-color-g0">@</span><span class="calendar-color-g2">@</span>  <span class="calendar-day"> 3</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 2, two stars" href="/2022/day/2" class="calendar-day2 calendar-verycomplete"><span class="calendar-color-s">-~------'</span><span class="calendar-color-u">    ~    ~ </span><span class="calendar-color-s">'--~-----~-~----___________--</span>  <span class="calendar-day"> 2</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
<a aria-label="Day 1, two stars" href="/2022/day/1" class="calendar-day1 calendar-verycomplete"><span class="calendar-color-u">  ~    ~  ~      ~     ~ ~   ~     ~  ~  ~   ~   </span>  <span class="calendar-day"> 1</span> <span class="calendar-mark-complete">*</span><span class="calendar-mark-verycomplete">*</span></a>
</pre>"#.to_owned();
        let stars = parse_http_response(calendar).unwrap();
        assert!(stars.pattern.len() == 25);
        assert!(stars.stars.len() == 25);
        assert!(stars
            .stars
            .iter()
            .all(|&solved_status| solved_status == SolvedParts::Both));
    }

    #[test]
    fn testing_stars() {
        let mut d = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
        d.push(format!("tests/resources/stars-page-full-stars.html"));
        let f = File::open(d).unwrap();
        let file_buf = BufReader::new(f);
        let stars: Stars = Stars::from_readable(file_buf).unwrap();
        let expected = r#"
  - /\ -  -        -       -     -      -    -
 - /  \/\  -    -     -  -    -   -  /\   -     -
 /\    \ \-  - -   -   -    - -  -/\/  \-   -  -   25 **
/@@\   /\@\@@@@@@@@@#@@#@#@@@@@@@#@@@##@@@@@#@#@#  24 **
@##.' '.#@@@#@@@@@@#@@#@@@##@#@@@##@##@@@@@@@@@@@  23 **
@#@'. .'@#@@.@@##@@@@@#####@@@@@##@@@@@#@()))@@@#  22 **
#@#@@@@####@@@#@##.@@@@@#@@#@@@##@@@@@@@#@@@@@@#@  21 **
#@@@@.@@#@#@@@@###@#@#@@.#@@~~@@@@@#@@@@#@@@@@@@#  20 **
#@@@@@##@#@@#.#@#@@@@##@#@@~~~~ .~'@@@##@@#@#@@@@  19 **
@#####@#@@@#@@.@@#@@@@@#@##@~~ /~\ ##@@#@####@#@|  18 **
##@@.@@#@@@#@@@..#@@@@@@@@@@@ / / \ #@@@@@##@#@@@  17 **
@@#@##@@#@@@@##@..@@##@@@@@#@/ / \ \@@@@@@@@@@###  16 **
@#@@#@@@@@@#@@#_.~._#@#@#@#@.'/\.'~. @#@@@@@#@@#@  15 **
#@#.@@@@@@@@@@@ ||| @#@@#@@'.~.'~. \'.@@@@@@@##@@  14 **
@@@@@@@@@@@#@@#@~~~@#@@@##@@' ..'.'.\. . #@@###@@  13 **
@@@@@@@#@@@@@#.~~.#@@#@#@@@@@@@@@ .'.~~~' @'@##@@  12 **
@@@.@#@#@@@@.~~.###@#@@@@@@@@#@@@@  ~~~~~..#@@@##  11 **
#@@.@##@@@#.~~.#@@@@@#@#@@@@@@@#@.'/ ~~~ \' @#@@#  10 **
#@@@.@@ _|%%%=%%|_ #@@@#@@#@@@@@. ~ /' .'/\.@@#@@   9 **
#@#@@../  \.~~./  \.....@@#@@###@' /\.''/' \' @#@   8 **
@@#@#@#@@@@.~~.@#@@@@@@#.@@##@#@'././\ .\'./\ '.    7 **
@@@@@@##@#@@.~~.@##@@#@..@@@##@' ~. \.\  \ \.~~~.   6 **
@@@#@@@@@@###.~~.##./\.'@@@@@@@@'.' .'/.@. /'.~~~   5 **
@@@##@@#@@#.' ~  './\'./\' .@@@@@#@' /\ . /'. ..'   4 **
@#@@#@@@#_/ ~   ~  \ ' '. '.'.@@@@  /  \  \  #@@@   3 **
-~------'    ~    ~ '--~-----~-~----___________--   2 **
  ~    ~  ~      ~     ~ ~   ~     ~  ~  ~   ~      1 **
"#
        .to_owned();
        std::iter::zip(expected.split("\n"), format!("\n{}", stars).split("\n")).for_each(
            |(expected, result)| {
                assert_eq!(expected, result.trim_end());
            },
        )
    }
}
